module.exports.bloodTestMetrics = {
  Creatinine: {
    category: 'Kidney Health',
    unit: 'mg/dL',
    optimalMin: 0.49, // this is the min of the optimal range for the metric
    optimalMax: 1.02, // this is the max of the optimal range for the metric
    directionOfGood: 'withinOptimalRange', // this is the desired for the metric. It can be withinOptimalRange, high, or low
    fullname: 'Creatinine',
    interpretation: 'Creatinine is a waste product from the normal breakdown of muscle tissue. As it is produced, creatinine is filtered through the kidneys and excreted in urine. Doctors measure the blood creatinine level as a test of kidney function.',
    interpretationLowAttention: 'A low creatinine level can indicate poor muscle mass, malnutrition, or a severe liver disease. It could also mean a condition that affects the flow of blood to your kidneys.', // this is the interpretation for the metric when it is low and needs attention
    interpretationHighAttention: 'A high creatinine level is usually a sign of kidney disease. The kidneys may not be working properly if you have high levels of creatinine in your blood.', // this is the interpretation for the metric when it is high and needs attention
    interpretationLowUrgent: 'Extremely low levels of creatinine could indicate a severe condition requiring immediate medical attention.', // this is the interpretation for the metric when it is extremely low and needs urgent attention
    interpretationHighUrgent: 'Extremely high levels of creatinine could indicate kidney failure or another serious condition requiring urgent medical intervention.' // this is the interpretation for the metric when it is extremely high and needs urgent attention
  },
  BUN: {
    category: 'Kidney Health',
    unit: 'mg/dL',
    optimalMin: 6,
    optimalMax: 20,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Blood Urea Nitrogen (BUN)',
    interpretation: 'BUN is a measure of the amount of nitrogen in the blood that comes from urea. Urea is a waste product formed by the liver from the breakdown of protein. BUN levels help evaluate kidney function.',
    interpretationLowAttention: 'Low BUN levels can indicate low protein intake, liver disease, or overhydration. Malnutrition can also cause low BUN.',
    interpretationHighAttention: 'Elevated BUN levels suggest impaired kidney function, which prevents the body from properly filtering urea out of the bloodstream. Dehydration and high protein diets can also increase BUN.',
    interpretationLowUrgent: 'Extremely low BUN requires medical evaluation to determine the underlying cause.',
    interpretationHighUrgent: 'Markedly high BUN indicates severe kidney dysfunction and requires urgent evaluation.'
  },
  eGFR: {
    category: 'Kidney Health',
    unit: 'mL/min',
    optimalMin: 100,
    attentionMin: 60,
    attentionMax: 100,
    urgentMax: 60,
    directionOfGood: 'high',
    fullname: 'Estimated Glomerular Filtration Rate (eGFR)',
    interpretation: 'eGFR estimates how much blood passes through the filters in your kidneys, called glomeruli, each minute. It is used to assess kidney function.',
    interpretationLowAttention: 'A decreased eGFR indicates mildly reduced kidney function. Lifestyle changes may help prevent further decline.',
    interpretationHighAttention: 'A mildly increased eGFR likely does not indicate kidney disease on its own. It should be monitored for changes.',
    interpretationLowUrgent: 'A significantly low eGFR indicates severely impaired kidney function requiring prompt evaluation and treatment.',
    interpretationHighUrgent: 'A significantly high eGFR is unusual and may indicate hyperfiltration damage to the kidneys.'
  },
  AST: {
    category: 'Liver',
    unit: 'U/L',
    optimalMax: 25,
    directionOfGood: 'low',
    fullname: 'Aspartate Aminotransferase (AST)',
    interpretation: 'AST is an enzyme found mostly in the liver, but also in smaller amounts in the kidneys, heart, muscles, and brain. Higher levels indicate liver injury.',
    interpretationLowAttention: 'Mildly low AST is generally harmless, but can occasionally signal a vitamin B6 deficiency.',
    interpretationHighAttention: 'Mildly elevated AST may indicate early liver damage from fatty liver disease, alcohol, toxins, or medications. Confirm with additional testing.',
    interpretationLowUrgent: 'Very low AST requires evaluation for muscle or liver disorders.',
    interpretationHighUrgent: 'High AST levels often indicate inflammation, infection, or serious liver damage. Prompt assessment is required.'
  },
  ALT: {
    category: 'Liver',
    unit: 'U/L',
    optimalMax: 25,
    directionOfGood: 'low',
    fullname: 'Alanine Aminotransferase (ALT)',
    interpretation: 'ALT is an enzyme found mostly in the liver. Elevated levels indicate liver injury.',
    interpretationLowAttention: 'Mildly low ALT is generally harmless, but can occasionally signal poor muscle health or malnutrition.',
    interpretationHighAttention: 'Mildly elevated ALT may indicate early liver damage from fatty liver disease, alcohol, toxins, or medications. Confirm with additional testing.',
    interpretationLowUrgent: 'Very low ALT requires evaluation for muscle or liver disorders.',
    interpretationHighUrgent: 'High ALT often signals inflammation, infection, or serious liver damage. Urgent assessment needed.'
  },
  Albumin: {
    category: 'Liver',
    unit: 'g/dL',
    optimalMin: 3.5,
    optimalMax: 5.2,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Albumin',
    interpretation: 'Albumin is a protein made by the liver. It is essential for maintaining fluid balance and transporting various compounds in the blood.',
    interpretationLowAttention: 'Mildly low albumin can indicate liver or kidney dysfunction, inflammation, or malnutrition requiring further evaluation.',
    interpretationHighAttention: 'Mildly high albumin is typically harmless in healthy people. Confirm with repeat testing.',
    interpretationLowUrgent: 'Very low albumin indicates severe liver or kidney dysfunction requiring prompt treatment.',
    interpretationHighUrgent: 'Very high albumin is abnormal and requires evaluation to determine the cause.'
  },
  AlkPhos: {
    category: 'Liver',
    unit: 'U/L',
    optimalMin: 36,
    optimalMax: 130,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Alkaline Phosphatase (AlkPhos)',
    interpretation: 'Alkaline phosphatase (ALP) is an enzyme found throughout the body, but primarily in the liver, bile ducts, and bones. Elevated ALP may indicate liver or bone disorders.',
    interpretationLowAttention: 'Mildly low ALP can suggest zinc or magnesium deficiency. Consider supplementing if low dietary intake.',
    interpretationHighAttention: 'Mildly high ALP may reflect liver dysfunction or bone disorders. Further testing is recommended.',
    interpretationLowUrgent: 'Markedly low ALP requires evaluation for severe nutritional deficiencies or bone disorders.',
    interpretationHighUrgent: 'Very elevated ALP often indicates serious liver or bone disease necessitating prompt assessment.'
  },
  GGT: {
    category: 'Liver',
    unit: 'U/L',
    optimalMin: 3,
    optimalMax: 90,
    directionOfGood: 'low',
    fullname: 'Gamma-glutamyl Transferase (GGT)',
    interpretation: 'GGT is an enzyme concentrated in the liver. Elevated GGT indicates liver injury or bile duct obstruction. Certain medications, alcohol use, and smoking can also increase levels.',
    interpretationLowAttention: 'Mildly low GGT is typically normal, but may indicate Wilson\'s disease in rare cases.',
    interpretationHighAttention: 'Mildly elevated GGT suggests possible liver dysfunction, medication side effects, or alcohol use. Further evaluation is recommended.',
    interpretationLowUrgent: 'Very low GGT requires assessment for liver dysfunction or Wilson\'s disease.',
    interpretationHighUrgent: 'Markedly elevated GGT often signals liver damage, bile duct obstruction, or heavy alcohol use. Prompt evaluation is needed.'
  },
  AGRatio: {
    category: 'Liver',
    unit: '(ratio)',
    optimalMin: 1.0,
    optimalMax: 2.5,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Albumin/Globulin Ratio',
    interpretation: 'The albumin to globulin (A/G) ratio compares blood levels of albumin (produced by the liver) to globulins (immune proteins). It helps assess liver and immune function.',
    interpretationLowAttention: 'A mildly low A/G ratio can indicate mild liver dysfunction or immune activation. Follow up testing may be needed.',
    interpretationHighAttention: 'A mildly elevated A/G ratio typically does not indicate a major problem. Check other liver tests.',
    interpretationLowUrgent: 'A significantly low A/G ratio often reflects serious liver disease requiring prompt evaluation.',
    interpretationHighUrgent: 'A markedly elevated A/G ratio may indicate a serious immune disorder. Prompt assessment recommended.'
  },
  BUNCreatinineRatio: {
    category: 'Liver',
    unit: '(ratio)',
    optimalMin: 6,
    optimalMax: 22,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Blood Urea Nitrogen/Creatinine Ratio',
    interpretation: 'The BUN to creatinine ratio compares blood urea nitrogen (BUN) to creatinine. It helps evaluate kidney function and fluid balance.',
    interpretationLowAttention: 'A mildly low ratio indicates possible overhydration. Increasing fluid intake may help normalize it.',
    interpretationHighAttention: 'A mildly elevated ratio suggests mild dehydration. Drinking more fluids may lower the ratio.',
    interpretationLowUrgent: 'An extremely low ratio requires evaluation for overhydration or liver dysfunction.',
    interpretationHighUrgent: 'A significantly elevated ratio indicates severe dehydration requiring urgent assessment and treatment.'
  },
  Bilirubin: {
    category: 'Liver',
    unit: 'mg/dL',
    optimalMin: 0.2,
    optimalMax: 1.2,
    directionOfGood: 'low',
    fullname: 'Bilirubin',
    interpretation: 'Bilirubin is produced by the liver and filtered out by the kidneys. Elevated levels indicate increased red blood cell breakdown or liver dysfunction.',
    interpretationLowAttention: 'Mildly low bilirubin is typically harmless but can occasionally indicate a bile duct obstruction.',
    interpretationHighAttention: 'Mildly elevated bilirubin may reflect liver dysfunction or inflammation. Further evaluation is recommended.',
    interpretationLowUrgent: 'Very low bilirubin requires assessment for possible liver or bile duct disease.',
    interpretationHighUrgent: 'Markedly elevated bilirubin often indicates severe liver dysfunction or bile obstruction requiring prompt evaluation.'
  },
  Globulin: {
    category: 'Liver',
    unit: 'g/dL',
    optimalMin: 1.9,
    optimalMax: 3.7,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Globulin',
    interpretation: 'Globulins are a class of proteins in the blood including antibodies. Levels help evaluate immune and liver function.',
    interpretationLowAttention: 'Mildly low globulin can suggest impaired immunity or liver dysfunction requiring follow up.',
    interpretationHighAttention: 'Mildly high globulin may indicate chronic inflammation or certain liver conditions. Further testing is recommended.',
    interpretationLowUrgent: 'Very low globulin often indicates liver failure or immune deficiency needing prompt assessment.',
    interpretationHighUrgent: 'Markedly high globulin levels can reflect serious liver disease or multiple myeloma requiring urgent evaluation.'
  },
  Protein: {
    category: 'Liver',
    unit: 'g/dL',
    optimalMin: 6.1,
    optimalMax: 8.1,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Total Protein',
    interpretation: 'Total protein is comprised of albumin produced by the liver and various other proteins. It evaluates liver and kidney function.',
    interpretationLowAttention: 'Mildly low protein may suggest impaired kidney or liver function warranting follow up testing.',
    interpretationHighAttention: 'Mildly elevated protein is typically normal but can indicate dehydration or multiple myeloma in certain cases.',
    interpretationLowUrgent: 'Very low protein often indicates nephrotic syndrome or severe liver dysfunction necessitating prompt assessment.',
    interpretationHighUrgent: 'Significantly elevated protein requires evaluation for causes like dehydration, kidney disease, or multiple myeloma.'
  },
  Sodium: {
    category: 'Electrolytes',
    unit: 'mmol/L',
    optimalMin: 135,
    optimalMax: 146,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Sodium',
    interpretation: 'Sodium is an electrolyte that helps regulate fluid balance, nerve impulse transmission, and muscle function. Unusual levels impair normal function.',
    interpretationLowAttention: 'Mild hyponatremia (low sodium) can cause fatigue, headache, muscle weakness. Increasing sodium intake may help.',
    interpretationHighAttention: 'Mild hypernatremia (high sodium) can cause thirst, headaches, confusion. Reducing sodium intake may help.',
    interpretationLowUrgent: 'Severely low sodium is dangerous and requires prompt treatment to prevent brain swelling, seizures, or death.',
    interpretationHighUrgent: 'Extremely high sodium often leads to severe dehydration requiring urgent treatment to prevent brain shrinkage or damage.'
  },
  Potassium: {
    category: 'Electrolytes',
    unit: 'mmol/L',
    optimalMin: 3.5,
    optimalMax: 5.3,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Potassium',
    interpretation: 'Potassium is an electrolyte important for nerve signals, muscle function, and heart rhythm. Abnormal levels impair normal function.',
    interpretationLowAttention: 'Mild hypokalemia can cause fatigue, muscle cramps, constipation. Increasing potassium intake may help normalize levels.',
    interpretationHighAttention: 'Mild hyperkalemia may cause muscle weakness or abnormal heart rhythms. Reducing potassium intake can help lower levels.',
    interpretationLowUrgent: 'Severely low potassium often leads to muscle paralysis, dangerous heart rhythms requiring prompt treatment.',
    interpretationHighUrgent: 'Extremely elevated potassium can be fatal, causing fatal heart rhythm abnormalities needing urgent treatment.'
  },
  Calcium: {
    category: 'Electrolytes',
    unit: 'mg/dL',
    optimalMin: 8.6,
    optimalMax: 10.3,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Calcium',
    interpretation: 'Calcium is essential for bone health and plays vital roles in muscle, nerve, and heart function. Abnormal levels can impair these functions.',
    interpretationLowAttention: 'Mild hypocalcemia can cause muscle spasms, tingling, fatigue. Increasing calcium intake may help normalize levels.',
    interpretationHighAttention: 'Mildly elevated calcium may not cause symptoms but increases risk of kidney stones or bone and heart disease.',
    interpretationLowUrgent: 'Severely low calcium can lead to seizures requiring urgent medical treatment.',
    interpretationHighUrgent: 'Dangerously high calcium increases the risk of abnormal heart rhythms and kidney failure necessitating prompt treatment.'
  },
  CarbonDioxide: {
    category: 'Electrolytes',
    unit: 'mmol/L',
    optimalMin: 20,
    optimalMax: 32,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Carbon Dioxide (CO2)',
    interpretation: 'CO2 level reflects acid-base balance in the blood. It is used to assess lung and kidney function.',
    interpretationLowAttention: 'Mildly low CO2 (acidosis) may indicate early kidney dysfunction or lung disease. Repeat labs and evaluation recommended.',
    interpretationHighAttention: 'Mildly elevated CO2 (alkalosis) can point to metabolic or lung conditions. Follow up testing is advisable.',
    interpretationLowUrgent: 'Markedly low CO2 indicates metabolic acidosis requiring urgent assessment and management.',
    interpretationHighUrgent: 'Extremely high CO2 reflects severe metabolic alkalosis and necessitates prompt treatment.'
  },
  Chloride: {
    category: 'Electrolytes',
    unit: 'mmol/L',
    optimalMin: 98,
    optimalMax: 110,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Chloride',
    interpretation: 'Chloride is an electrolyte that helps maintain fluid balance. Abnormal levels impair the distribution of fluids in the body.',
    interpretationLowAttention: 'Mildly low chloride can cause muscle cramps. Increasing chloride intake may help normalize levels.',
    interpretationHighAttention: 'Mildly high chloride typically causes minimal symptoms. Lowering chloride intake may help.',
    interpretationLowUrgent: 'Severely low chloride often requires intravenous fluids or diuretic adjustment.',
    interpretationHighUrgent: 'Extremely high chloride is associated with dehydration requiring prompt management.'
  },
  Hematocrit: {
    category: 'Blood Counts',
    unit: '%',
    optimalMin: 38.5,
    optimalMax: 50.0,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Hematocrit',
    interpretation: 'Hematocrit measures the percentage of red blood cells in the blood. It is used to diagnose anemia, polycythemia, and dehydration.',
    interpretationLowAttention: 'A mildly decreased hematocrit indicates mild anemia. Increasing iron intake or testing for sources of blood loss may help.',
    interpretationHighAttention: 'A mildly elevated hematocrit is typically normal but can suggest mild dehydration. Increasing fluid intake may help.',
    interpretationLowUrgent: 'A significantly decreased hematocrit often indicates severe iron deficiency or blood loss warranting prompt follow up.',
    interpretationHighUrgent: 'A markedly elevated hematocrit requires prompt evaluation for polycythemia vera or severe dehydration.'
  },
  Hemoglobin: {
    category: 'Blood Counts',
    unit: 'g/dL',
    optimalMin: 13.2,
    optimalMax: 17.1,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Hemoglobin',
    interpretation: 'Hemoglobin transports oxygen in the blood. Low levels indicate anemia while elevated levels suggest dehydration or lung disease.',
    interpretationLowAttention: 'Mildly decreased hemoglobin indicates mild anemia. Increasing iron intake or testing for blood loss may help.',
    interpretationHighAttention: 'Mildly elevated hemoglobin is typically normal but may suggest mild dehydration. Drink more fluids.',
    interpretationLowUrgent: 'Significantly low hemoglobin often reflects severe iron deficiency or blood loss warranting prompt follow up.',
    interpretationHighUrgent: 'Markedly elevated hemoglobin is abnormal and requires evaluation for underlying causes like polycythemia vera or COPD.'
  },
  MCV: {
    category: 'Blood Counts',
    unit: 'fL',
    optimalMin: 80.0,
    optimalMax: 100.0,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Mean Corpuscular Volume (MCV)',
    interpretation: 'MCV measures the average size of red blood cells. It is used to classify types of anemia.',
    interpretationLowAttention: 'Mildly decreased MCV indicates the possibility of iron deficiency anemia or thalassemia. Further testing is recommended.',
    interpretationHighAttention: 'Mildly elevated MCV suggests macrocytic anemia. Additional testing should be done.',
    interpretationLowUrgent: 'Very low MCV requires prompt assessment for causes like severe iron deficiency.',
    interpretationHighUrgent: 'Markedly high MCV necessitates urgent evaluation for underlying causes like vitamin B12 deficiency.'
  },
  MCH: {
    category: 'Blood Counts',
    unit: 'pg',
    optimalMin: 27.0,
    optimalMax: 33.0,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Mean Corpuscular Hemoglobin (MCH)',
    interpretation: 'MCH measures the average amount of hemoglobin per red blood cell. It is used to classify types of anemia.',
    interpretationLowAttention: 'Mildly decreased MCH indicates possible iron deficiency anemia. Further testing should be done.',
    interpretationHighAttention: 'Mildly elevated MCH is typically normal and requires no action unless other RBC indices are abnormal.',
    interpretationLowUrgent: 'Significantly decreased MCH often reflects severe iron deficiency requiring prompt follow up.',
    interpretationHighUrgent: 'Markedly elevated MCH is unusual and warrants evaluation to determine the underlying cause.'
  },
  MCHC: {
    category: 'Blood Counts',
    unit: 'g/dL',
    optimalMin: 32.0,
    optimalMax: 36.0,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Mean Corpuscular Hemoglobin Concentration (MCHC)',
    interpretation: 'MCHC measures the average concentration of hemoglobin within red blood cells. It is used to classify types of anemia.',
    interpretationLowAttention: 'Mildly decreased MCHC can indicate iron deficiency anemia or other conditions. Repeat testing is recommended.',
    interpretationHighAttention: 'Mildly elevated MCHC is typically normal and requires no action unless other RBC indices are abnormal.',
    interpretationLowUrgent: 'Significantly decreased MCHC often indicates severe iron deficiency anemia necessitating prompt evaluation.',
    interpretationHighUrgent: 'Markedly elevated MCHC requires assessment to determine the underlying cause.'
  },
  RedCellDistributionWidth: {
    category: 'Blood Counts',
    unit: '%',
    optimalMin: 12,
    optimalMax: 15.5,
    directionOfGood: 'low',
    fullname: 'Red Cell Distribution Width (RDW)',
    interpretation: 'RDW measures variation in red blood cell size. Elevated RDW indicates greater variation in size (anisocytosis).',
    interpretationLowAttention: 'Mildly decreased RDW is normal.',
    interpretationHighAttention: 'Mildly elevated RDW may indicate nutritional deficiency or early anemia. Repeat testing is recommended.',
    interpretationLowUrgent: 'A significantly low RDW is unusual and warrants evaluation.',
    interpretationHighUrgent: 'Markedly elevated RDW often reflects severe nutritional deficiency, anemia, or other serious conditions requiring prompt assessment.'
  },
  Neutrophils: {
    category: 'Blood Counts',
    unit: '%',
    optimalMin: 37.1,
    optimalMax: 78.1,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Neutrophils',
    interpretation: 'Neutrophils are a type of white blood cell that fights bacterial infections. Levels usually increase with inflammation or infection.',
    interpretationLowAttention: 'Mild neutropenia may increase infection risk slightly. Repeat testing is advised.',
    interpretationHighAttention: 'Mild neutrophilia is often normal. If elevated, it can indicate infection, inflammation, or stress.',
    interpretationLowUrgent: 'Severe neutropenia significantly increases the risk of serious infections requiring prompt evaluation.',
    interpretationHighUrgent: 'Marked neutrophilia often signals a severe inflammatory or infectious process necessitating urgent assessment.'
  },
  Lymphocytes: {
    category: 'Blood Counts',
    unit: '%',
    optimalMin: 13.7,
    optimalMax: 50.9,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Lymphocytes',
    interpretation: 'Lymphocytes are a type of white blood cell involved in immune response. Levels can increase or decrease based on immune activation or suppression.',
    interpretationLowAttention: 'Mild lymphopenia may slightly increase infection risk. Repeat testing recommended.',
    interpretationHighAttention: 'Mild lymphocytosis is often normal but can indicate infection or inflammation. If elevated, further evaluation may be needed.',
    interpretationLowUrgent: 'Severe lymphopenia significantly raises infection risk, necessitating prompt assessment.',
    interpretationHighUrgent: 'Marked lymphocytosis is abnormal and requires urgent follow up to determine the underlying cause.'
  },
  Monocytes: {
    category: 'Blood Counts',
    unit: '%',
    optimalMin: 3.0,
    optimalMax: 11.9,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Monocytes',
    interpretation: 'Monocytes are a type of white blood cell that fight infections, remove dead cells, and stimulate immune response. Levels typically rise with inflammation.',
    interpretationLowAttention: 'Mild monocytopenia is usually normal with minimal clinical impact.',
    interpretationHighAttention: 'Mild monocytosis may indicate chronic inflammation requiring further evaluation if persistent. ',
    interpretationLowUrgent: 'Significantly decreased monocytes can reflect an immunocompromised state necessitating prompt assessment.',
    interpretationHighUrgent: 'Markedly elevated monocytes often signals serious inflammatory disease or blood disorders requiring urgent follow up.'
  },
  Eosinophils: {
    category: 'Blood Counts',
    unit: '%',
    optimalMax: 5,
    directionOfGood: 'low',
    fullname: 'Eosinophils',
    interpretation: 'Eosinophils are a type of white blood cell involved in allergic reactions and responses to parasites. Levels increase with these conditions.',
    interpretationLowAttention: 'Mild eosinopenia is typically normal with minimal clinical significance.',
    interpretationHighAttention: 'Mild eosinophilia often indicates parasite infection, allergies, or asthma. Avoiding triggers may help lower levels.',
    interpretationLowUrgent: 'Profoundly low eosinophils require evaluation, though this rarely occurs.',
    interpretationHighUrgent: 'Extremely elevated eosinophils are abnormal and warrant urgent assessment for serious underlying disorder.'
  },
  Basophils: {
    category: 'Blood Counts',
    unit: '%',
    optimalMax: 1,
    directionOfGood: 'low',
    fullname: 'Basophils',
    interpretation: 'Basophils are a rare type of white blood cell. They are involved in allergic reactions and protecting against parasites. Levels increase with these conditions.',
    interpretationLowAttention: 'Mild basopenia is common and typically insignificant unless other cell lines are affected.',
    interpretationHighAttention: 'Mildly elevated basophils can indicate chronic allergic reaction or parasitic infection. Avoiding triggers may help.',
    interpretationLowUrgent: 'Significantly decreased basophils are uncommon but warrant evaluation.',
    interpretationHighUrgent: 'Marked basophilia is abnormal and requires prompt assessment to determine the underlying cause.'
  },
  PlatletCounts: {
    category: 'Blood Counts',
    unit: 'Thousand/uL',
    optimalMin: 140,
    optimalMax: 400,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Platelet Count',
    interpretation: 'Platelets help the blood clot. Too few can lead to excessive bleeding while too many increase clotting risk.',
    interpretationLowAttention: 'Mild thrombocytopenia slightly raises bleeding risk. Avoiding blood thinners can help prevent bleeding issues.',
    interpretationHighAttention: 'Mild thrombocytosis typically causes no symptoms but can increase clotting risk long-term.',
    interpretationLowUrgent: 'Severely decreased platelets substantially increase bleeding risk, necessitating prompt evaluation and care.',
    interpretationHighUrgent: 'Significantly elevated platelets require urgent follow up as they elevate clotting risk.'
  },
  RedCellCount: {
    category: 'Blood Counts',
    unit: 'Million/uL',
    optimalMin: 4.20,
    optimalMax: 5.80,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Red Blood Cell Count',
    interpretation: 'Red blood cell (RBC) count gauges the number of RBCs in the blood. RBCs carry oxygen throughout the body.',
    interpretationLowAttention: 'Mildly decreased RBC count indicates mild anemia. Increasing iron intake or testing for blood loss may help.',
    interpretationHighAttention: 'Mildly elevated RBC count is typically normal but can suggest mild dehydration. Drink more fluids.',
    interpretationLowUrgent: 'Significantly decreased RBC count often reflects severe iron deficiency or blood loss requiring prompt follow up.',
    interpretationHighUrgent: 'Markedly elevated RBC count is abnormal and necessitates evaluation for underlying causes like COPD.'
  },
  WhiteCellCount: {
    category: 'Blood Counts',
    unit: 'Thousand/uL',
    optimalMin: 3.8,
    optimalMax: 10.8,
    directionOfGood: 'withinOptimalRange',
    fullname: 'White Blood Cell Count',
    interpretation: 'White blood cells fight infection and disease. High levels usually indicate infection or inflammation.',
    interpretationLowAttention: 'Mild leukopenia may slightly increase infection risk. Repeat testing is recommended.',
    interpretationHighAttention: 'Mild leukocytosis can reflect infection, inflammation, stress, or medication use. Further testing may be needed.',
    interpretationLowUrgent: 'Severe leukopenia significantly raises the risk of serious infection requiring prompt evaluation.',
    interpretationHighUrgent: 'Extreme leukocytosis is abnormal and necessitates urgent assessment to determine the underlying cause.'
  },
  LDLC: {
    category: 'Cardiac Labs',
    unit: 'mg/dL',
    optimalMax: 100,
    directionOfGood: 'low',
    fullname: 'LDL Cholesterol',
    interpretation: 'LDL cholesterol builds up on artery walls, increasing risk of heart attack and stroke. Lower levels are associated with lower cardiac risk.',
    interpretationLowAttention: 'Mildly low LDL is considered optimal to lower cardiac risk, but very low levels may heighten risk for hemorrhagic stroke.',
    interpretationHighAttention: 'Mildly elevated LDL increases the risk of atherosclerosis. Diet and exercise modifications, or medication if needed, can lower levels.',
    interpretationLowUrgent: 'Profoundly low LDL is abnormal and requires evaluation to determine if due to familial hypobetalipoproteinemia.',
    interpretationHighUrgent: 'Markedly elevated LDL cholesterol significantly increases cardiac risk, necessitating prompt medical treatment.'
  },
  ApoB: {
    category: 'Cardiac Labs',
    unit: 'mg/dL',
    optimalMax: 60,
    attentionMin: 60,
    attentionMax: 89,
    urgentMin: 89,
    directionOfGood: 'low',
    fullname: 'Apolipoprotein B',
    interpretation: 'ApoB indicates the number of LDL particles carrying cholesterol in the blood. Higher levels indicate increased risk of atherosclerosis.',
    interpretationLowAttention: 'Mildly low ApoB is optimal.',
    interpretationHighAttention: 'Mildly elevated ApoB indicates moderately increased cardiac risk. Treatment to lower levels can help reduce risk.',
    interpretationLowUrgent: 'Very low ApoB is unusual and warrants evaluation but is likely not dangerous on its own.',
    interpretationHighUrgent: 'Markedly elevated ApoB significantly increases cardiovascular risk, necessitating urgent treatment.'
  },
  HsCRP: {
    category: 'Cardiac Labs',
    unit: 'mg/dL',
    fullname: 'High Sensitivity C-Reactive Protein',
    optimalMax: 1,
    directionOfGood: 'low',
    interpretation: 'hs-CRP measures inflammation levels and predicts cardiac risk even when cholesterol is normal. Lower levels are preferable.',
    interpretationLowAttention: 'Mildly decreased hs-CRP is optimal.',
    interpretationHighAttention: 'Mildly elevated hs-CRP indicates increased inflammation and cardiac risk. Anti-inflammatory lifestyle changes and fish oil supplements may help lower levels.',
    interpretationLowUrgent: 'Significantly low hs-CRP is unusual but likely not dangerous on its own.',
    interpretationHighUrgent: 'Markedly elevated hs-CRP requires prompt medical evaluation to determine if acute infection or critical illness is present.',
  },
  Homocysteine: {
    category: 'Cardiac Labs',
    unit: 'micromol/L',
    optimalMax: 7,
    attentionMin: 8,
    attentionMax: 12,
    urgentMin: 13,
    directionOfGood: 'low',
    fullname: 'Homocysteine',
    interpretation: 'Homocysteine is an amino acid linked to atherosclerosis, blood clots, and dementia. Lower levels are associated with lower risk.',
    interpretationLowAttention: 'Mildly decreased homocysteine is optimal.',
    interpretationHighAttention: 'Mildly elevated homocysteine slightly increases cardiovascular risk and cognitive decline risk. B vitamins can help lower levels.',
    interpretationLowUrgent: 'Very low homocysteine is unusual but likely not dangerous if not accompanied by other hematologic abnormalities.',
    interpretationHighUrgent: 'Markedly elevated homocysteine significantly increases risk of atherosclerosis and dementia. Prompt medical treatment is warranted.',
  },
  LpA: {
    category: 'Cardiac Labs',
    unit: 'nmol/L',
    lowRisk: {
      optimalMax: 50,
      attentionMin: 50,
      attentionMax: 125,
      urgentMin: 125,
      directionOfGood: 'low'
    },
    highRisk: {
      optimalMax: 35,
      attentionMin: 35,
      attentionMax: 75,
      urgentMin: 75,
      directionOfGood: 'low'
    },
    fullname: 'Lipoprotein(a)',
    interpretation: 'Lp(a) is an LDL particle associated with increased risk of atherosclerosis. Lower levels are preferable, especially in those with high cardiac risk.',
    interpretationLowAttention: 'Mildly low Lp(a) is optimal.',
    interpretationHighAttention: 'Mildly elevated Lp(a) indicates moderately increased cardiac risk. LDL lowering treatment can help lower levels.',
    interpretationLowUrgent: 'Profoundly low Lp(a) is unusual but likely not dangerous if not accompanied by other lipid abnormalities.',
    interpretationHighUrgent: 'Markedly elevated Lp(a) significantly increases cardiac risk and typically warrants prompt medical treatment to lower levels.'
  },
  Triglycerides: {
    category: 'Cardiac Labs',
    unit: 'mg/dL',
    optimalMax: 100,
    directionOfGood: 'low',
    fullname: 'Triglycerides',
    interpretation: 'Triglycerides store fat in the body. Excess levels increase risk of atherosclerosis.',
    interpretationLowAttention: 'Mildly decreased triglycerides are optimal.',
    interpretationHighAttention: 'Mildly high triglycerides increase cardiac risk, especially when HDL is low and LDL high. Diet and exercise can help lower levels.',
    interpretationLowUrgent: 'Dangerously low triglycerides (<10 mg/dL) can cause pancreatitis requiring urgent care.',
    interpretationHighUrgent: 'Severely elevated triglycerides substantially increase cardiovascular risk and can cause pancreatitis. Prompt medical treatment is necessary.'
  },
  HDLC: {
    category: 'Cardiac Labs',
    unit: 'mg/dL',
    optimalMin: 50,
    directionOfGood: 'high',
    fullname: 'HDL Cholesterol',
    interpretation: 'HDL helps remove cholesterol from arteries. Higher levels are associated with lower cardiac risk.',
    interpretationLowAttention: 'Mildly decreased HDL moderately increases cardiac risk. Exercise and niacin supplements can help raise levels.',
    interpretationHighAttention: 'Mildly elevated HDL is optimal. However, extremely high levels can indicate HDL dysfunction.',
    interpretationLowUrgent: 'Severely low HDL significantly raises cardiovascular risk and requires prompt medical treatment.',
    interpretationHighUrgent: 'Markedly elevated HDL is abnormal and warrants medical evaluation to determine if due to rare genetic disorders or liver disease.'
  },
  TotalCholesterol: {
    category: 'Cardiac Labs',
    unit: 'mg/dL',
    optimalMax: 200,
    attentionMin: 200,
    directionOfGood: 'low',
    fullname: 'Total Cholesterol',
    interpretation: 'Total cholesterol is composed of HDL, LDL, VLDL and chylomicrons. Elevated total cholesterol increases cardiac risk.',
    interpretationLowAttention: 'Mildly low total cholesterol is optimal for cardiovascular health.',
    interpretationHighAttention: 'Mildly high total cholesterol raises cardiac risk modestly. Diet, exercise and medication if needed can help lower levels.',
    interpretationLowUrgent: 'Severely low total cholesterol is abnormal and warrants medical evaluation.',
    interpretationHighUrgent: 'Markedly elevated total cholesterol significantly increases atherosclerosis risk and requires prompt medical treatment.'
  },
  FastingGlucose: {
    category: 'Glycemic Control',
    unit: 'mg/dL',
    optimalMax: 86,
    attentionMin: 100,
    attentionMax: 120,
    urgentMin: 120,
    directionOfGood: 'low',
    fullname: 'Fasting Glucose',
    interpretation: 'Fasting glucose indicates diabetes risk. Higher levels are associated with greater risk of developing diabetes and its complications.',
    interpretationLowAttention: 'Mildly decreased fasting glucose is optimal for diabetes prevention.',
    interpretationHighAttention: 'Mildly elevated fasting glucose indicates prediabetes and heightened diabetes risk. Lifestyle changes can help lower levels.',
    interpretationLowUrgent: 'Markedly low fasting glucose can cause recurrent hypoglycemic episodes requiring urgent evaluation.',
    interpretationHighUrgent: 'Significantly elevated fasting glucose indicates diabetes. Prompt treatment is necessary to prevent long-term complications.'
  },
  TriglyceridesHDLCRatio: {
    category: 'Glycemic Control',
    unit: '(ratio)',
    optimalMax: 1,
    attentionMax: 2,
    urgentMin: 2,
    directionOfGood: 'low',
    fullname: 'Triglyceride to HDL Ratio',
    interpretation: 'This ratio screens for insulin resistance, a precursor to diabetes. Lower ratios are ideal.',
    interpretationLowAttention: 'A mildly low ratio is optimal.',
    interpretationHighAttention: 'A mildly elevated ratio indicates moderate insulin resistance and increased diabetes risk. Diet, exercise and metformin can improve insulin sensitivity.',
    interpretationLowUrgent: 'An extremely low ratio is abnormal and warrants evaluation but is not dangerous on its own.',
    interpretationHighUrgent: 'A markedly elevated ratio reflects severe insulin resistance necessitating prompt medical treatment.'
  },
  A1C: {
    category: 'Glycemic Control',
    unit: '%',
    optimalMax: 5.6,
    attentionMin: 5.6,
    attentionMax: 6.4,
    urgentMin: 6.5,
    directionOfGood: 'low',
    fullname: 'Hemoglobin A1C',
    interpretation: 'Hemoglobin A1C reflects average blood glucose over the past 2-3 months. Higher levels indicate poorer blood sugar control and diabetes risk.',
    interpretationLowAttention: 'Mildly decreased A1C is optimal for diabetes prevention.',
    interpretationHighAttention: 'Mildly elevated A1C indicates heightened diabetes risk or early diabetes if over 6.4%. Lifestyle changes and metformin can help lower levels.',
    interpretationLowUrgent: 'Dangerously low A1C (<4%) can indicate rapid red blood cell turnover and requires prompt evaluation.',
    interpretationHighUrgent: 'Markedly elevated A1C (over 9%) indicates poorly controlled diabetes necessitating urgent treatment modification to prevent complications.'
  },
  FastingInsulin: {
    category: 'Glycemic Control',
    unit: 'μU/mL',
    optimalMax: 6,
    directionOfGood: 'low',
    fullname: 'Fasting Insulin',
    interpretation: 'Fasting insulin indicates insulin resistance. Higher levels are associated with greater diabetes risk.',
    interpretationLowAttention: 'Mildly decreased fasting insulin is optimal for diabetes prevention.',
    interpretationHighAttention: 'Mildly elevated fasting insulin indicates insulin resistance and heightened diabetes risk. Lifestyle changes and metformin can lower levels.',
    interpretationLowUrgent: 'Profoundly low fasting insulin warrants evaluation for insulinopenic diabetes or pancreatic insufficiency.',
    interpretationHighUrgent: 'Markedly elevated fasting insulin reflects significant insulin resistance. Prompt treatment with lifestyle changes, metformin, or insulin sensitizers is needed.'
  },
  HOMOIR: {
    category: 'Glycemic Control',
    unit: '(ratio)',
    optimalMax: 1.0,
    attentionMin: 1.9,
    urgentMin: 2.9,
    directionOfGood: 'low',
    fullname: 'HOMA-IR',
    interpretation: 'HOMA-IR gauges insulin resistance, an early predictor of diabetes. Lower levels reflect better insulin sensitivity.',
    interpretationLowAttention: 'A mildly low HOMA-IR is optimal.',
    interpretationHighAttention: 'A mildly elevated HOMA-IR indicates moderate insulin resistance and increased diabetes risk. Lifestyle and metformin can help improve insulin sensitivity.',
    interpretationLowUrgent: 'An extremely low HOMA-IR can indicate insulin deficiency requiring prompt evaluation.',
    interpretationHighUrgent: 'A markedly elevated HOMA-IR reflects severe insulin resistance necessitating urgent treatment with lifestyle changes, metformin and possibly insulin sensitizers.'
  },
  VitaminD: {
    category: 'Other',
    unit: 'ng/mL',
    optimalMin: 40,
    optimalMax: 80,
    directionOfGood: 'withinOptimalRange',
    fullname: '25-hydroxy Vitamin D',
    interpretation: 'Vitamin D is essential for bone health and immune function. Inadequate levels are associated with many chronic diseases.',
    interpretationLowAttention: 'Mildly decreased vitamin D indicates insufficient levels. Supplementation around 2000 IU daily is recommended.',
    interpretationHighAttention: 'Mildly elevated vitamin D is usually safe but can predispose to hypercalcemia and kidney stones in some people.',
    interpretationLowUrgent: 'Profound vitamin D deficiency (<10 ng/mL) causes rickets in children and osteomalacia in adults requiring prompt treatment with high dose supplementation.',
    interpretationHighUrgent: 'Markedly elevated vitamin D (>150 ng/mL) can cause hypercalcemia with kidney and cardiovascular damage necessitating urgent treatment.'
  },
  Ferritin: {
    category: 'Other',
    unit: 'ng/dL',
    optimalMin: 50,
    optimalMax: 100,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Ferritin',
    interpretation: 'Ferritin is a protein storing iron in the body. Measuring ferritin helps evaluate iron levels and inflammation.',
    interpretationLowAttention: 'Mildly low ferritin may indicate depleted iron stores warranting increased dietary iron intake.',
    interpretationHighAttention: 'Mildly elevated ferritin often reflects inflammation but can also indicate excess iron stores. Reducing inflammation and monitoring iron studies is recommended.',
    interpretationLowUrgent: 'Profoundly low ferritin (<10 ng/mL) indicates iron deficiency requiring intravenous iron infusion or blood transfusion in severe cases.',
    interpretationHighUrgent: 'Markedly high ferritin (>500 ng/mL) suggests iron overload requiring prompt evaluation and phlebotomy treatment if confirmed on further testing.'
  },
  UricAcid: {
    category: 'Other',
    unit: 'mg/dL',
    male: {
      optimalMin: 3.6,
      optimalMax: 5.4,
      attentionMin: 3.5,
      attentionMax: 5.5,
      urgentMin: 7,
      directionOfGood: 'withinOptimalRange'
    },
    female: {
      optimalMin: 2.6,
      optimalMax: 4.9,
      attentionMin: 2.5,
      attentionMax: 5,
      urgentMin: 6,
      directionOfGood: 'withinOptimalRange'
    },
    fullname: 'Uric Acid',
    interpretation: 'Uric acid is a product of purine breakdown. Abnormal levels can indicate gout or kidney stones risk.',
    interpretationLowAttention: 'Mildly low uric acid is common in the elderly but may increase neurodegenerative disease risk.',
    interpretationHighAttention: 'Mildly elevated uric acid indicates moderately increased gout and kidney stone risk. Limiting meat and seafood intake may help lower levels.',
    interpretationLowUrgent: 'Markedly low uric acid can reflect a rare enzymatic defect requiring prompt evaluation.',
    interpretationHighUrgent: 'Severely elevated uric acid levels can cause gout flares or kidney stones necessitating urgent treatment.'
  },
  TSH: {
    category: 'Other',
    unit: 'mIU/L',
    optimalMin: 1,
    optimalMax: 2,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Thyroid Stimulating Hormone (TSH)',
    interpretation: 'TSH measures thyroid function. Elevated TSH indicates hypothyroidism while low TSH suggests hyperthyroidism.',
    interpretationLowAttention: 'Mild TSH suppression likely indicates subclinical hyperthyroidism that should be monitored for progression.',
    interpretationHighAttention: 'Mild TSH elevation typically indicates mild hypothyroidism. Thyroid hormone replacement medication can restore normal function.',
    interpretationLowUrgent: 'Profound TSH suppression warrants prompt evaluation for Graves disease, thyroiditis, or pituitary dysfunction.',
    interpretationHighUrgent: 'Markedly elevated TSH signifies severe hypothyroidism necessitating urgent thyroid hormone replacement therapy.'
  },
  DHEAS: {
    category: 'Other',
    unit: 'mg/dL',
    male: {
      optimalMin: 400,
      optimalMax: 500,
      directionOfGood: 'withinOptimalRange'
    },
    female: {
      optimalMin: 350,
      optimalMax: 430,
      directionOfGood: 'withinOptimalRange'
    },
    fullname: 'DHEA-Sulfate',
    interpretation: 'DHEA-S is a precursor sex steroid hormone that declines with age. Normal levels help maintain vitality, metabolism, libido, and bone density.',
    interpretationLowAttention: 'Mildly decreased DHEA-S may reflect aging but can also indicate adrenal dysfunction requiring further evaluation.',
    interpretationHighAttention: 'Mildly elevated DHEA-S usually does not cause symptoms but may indicate PCOS or adrenal hyperplasia in females, or adrenal tumors if markedly high.',
    interpretationLowUrgent: 'Profoundly low DHEA-S suggests adrenal failure necessitating prompt treatment and evaluation for adrenal insufficiency.',
    interpretationHighUrgent: 'Markedly elevated DHEA-S requires urgent evaluation for adrenal tumor, especially if testosterone levels are also elevated.'
  },
  VitaminB12: {
    category: 'Other',
    unit: 'pg/mL',
    optimalMin: 500,
    optimalMax: 1500,
    directionOfGood: 'withinOptimalRange',
    fullname: 'Vitamin B12',
    interpretation: 'Vitamin B12 is essential for neurological function and red blood cell formation. Low levels can cause anemia, fatigue, and cognitive impairment.',
    interpretationLowAttention: 'Mildly decreased vitamin B12 indicates depletion warranting oral supplementation.',
    interpretationHighAttention: 'Mildly elevated vitamin B12 is typically normal but can result from liver disease or certain blood cancers in some cases.',
    interpretationLowUrgent: 'Profound vitamin B12 deficiency (<200 pg/mL) can lead to irreversible neurological damage necessitating prompt intramuscular B12 treatment.',
    interpretationHighUrgent: 'Markedly elevated vitamin B12 levels are abnormal and require evaluation for underlying liver disease or hematologic malignancies.'
  },
  PSA: {
    category: 'Other',
    unit: 'ng/mL',
    optimalMax: 4.00,
    directionOfGood: 'low',
    fullname: 'Prostate Specific Antigen (PSA)',
    interpretation: 'PSA is used as a screening test for prostate cancer in men. Elevated levels warrant further diagnostic testing for prostate cancer.',
    interpretationLowAttention: 'Mildly low PSA is optimal.',
    interpretationHighAttention: 'Mildly elevated PSA may indicate prostate enlargement or inflammation but also warrants further cancer evaluation via rectal exam and potential prostate biopsy if levels are rising.',
    interpretationLowUrgent: 'Markedly decreased PSA is abnormal but the cause is unclear.',
    interpretationHighUrgent: 'Significantly elevated PSA (>10 ng/mL) indicates high likelihood of prostate cancer necessitating urgent urologic evaluation and biopsy.'
  }
}
